"""
Plot suppressor-voltage sweep results for the Faraday cup secondary-electron
hopping simulator.

This script reads the CSV generated by scripts/sweep_suppressor_voltage.py,
aggregates results across random seeds, and saves summary plots showing how
hopping and return probabilities change with suppressor voltage.
"""

import csv
from collections import defaultdict
from pathlib import Path
from statistics import fmean, stdev

import matplotlib.pyplot as plt

INPUT_PATH = Path("data/processed/suppressor_voltage_sweep.csv")
OUTPUT_DIR = Path("figures")


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        return list(reader)


def group_rows_by_voltage(
    rows: list[dict[str, str]],
) -> dict[float, list[dict[str, str]]]:
    grouped_rows = defaultdict(list)

    for row in rows:
        suppressor_voltage = float(row["suppressor_voltage"])
        grouped_rows[suppressor_voltage].append(row)

    return dict(grouped_rows)


def mean_and_std(values: list[float]) -> tuple[float, float]:
    if len(values) == 1:
        return values[0], 0.0

    return fmean(values), stdev(values)


def aggregate_metric_by_voltage(
    grouped_rows: dict[float, list[dict[str, str]]],
    metric_name: str,
) -> tuple[list[float], list[float], list[float]]:
    voltages = []
    means = []
    stds = []

    for voltage in sorted(grouped_rows):
        values = [float(row[metric_name]) for row in grouped_rows[voltage]]

        mean_value, std_value = mean_and_std(values)

        voltages.append(voltage)
        means.append(mean_value)
        stds.append(std_value)

    return voltages, means, stds


def plot_metric(
    grouped_rows: dict[float, list[dict[str, str]]],
    metric_name: str,
    y_label: str,
    title: str,
    output_path: Path,
) -> None:
    voltages, means, stds = aggregate_metric_by_voltage(
        grouped_rows=grouped_rows,
        metric_name=metric_name,
    )

    plt.figure(figsize=(7, 5))

    plt.errorbar(
        voltages,
        means,
        yerr=stds,
        marker="o",
        capsize=4,
    )

    plt.xlabel("Suppressor voltage (V)")
    plt.ylabel(y_label)
    plt.title(title)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()

    plt.savefig(output_path, dpi=300)
    plt.close()


def main() -> None:
    rows = load_rows(INPUT_PATH)
    grouped_rows = group_rows_by_voltage(rows)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    plot_metric(
        grouped_rows=grouped_rows,
        metric_name="ion_hopping_probability",
        y_label="Ion hopping probability",
        title="Ion hopping probability vs suppressor voltage",
        output_path=OUTPUT_DIR / "ion_hopping_vs_suppressor_voltage.png",
    )

    plot_metric(
        grouped_rows=grouped_rows,
        metric_name="electron_hopping_probability",
        y_label="Electron hopping probability",
        title="Electron hopping probability vs suppressor voltage",
        output_path=OUTPUT_DIR / "electron_hopping_vs_suppressor_voltage.png",
    )

    plot_metric(
        grouped_rows=grouped_rows,
        metric_name="return_probability",
        y_label="Return probability",
        title="Return probability vs suppressor voltage",
        output_path=OUTPUT_DIR / "return_probability_vs_suppressor_voltage.png",
    )

    print(f"Saved plots to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
